import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
//import styles from '../styles/portfolio.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="container">
        <div class="item item-a">
            <h2>Primeiro Box</h2>
                <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
                Neque molestias eum dolor distinctio ea recusandae! Consequatur 
                sunt, dolore eos nemo minus, eveniet itaque in blanditiis iure 
                rerum, ipsum pariatur placeat!
                </p>
        </div>

        <div class="item item-b">
            <h2>Segundo Box</h2>
                <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
                Neque molestias eum dolor distinctio ea recusandae! Consequatur 
                sunt, dolore eos nemo minus, eveniet itaque in blanditiis iure 
                rerum, ipsum pariatur placeat!
                </p>
        </div>
        
        <div class="item item-c">
            <h2>Terceiro Box</h2>
                <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
                Neque molestias eum dolor distinctio ea recusandae! Consequatur 
                sunt, dolore eos nemo minus, eveniet itaque in blanditiis iure 
                rerum, ipsum pariatur placeat!
                </p>
        </div>
        
        <div class="item item-d">
            <h2>Quarto Box</h2>
                <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
                Neque molestias eum dolor distinctio ea recusandae! Consequatur 
                sunt, dolore eos nemo minus, eveniet itaque in blanditiis iure 
                rerum, ipsum pariatur placeat!
                </p>
        </div>
        
        <div class="item item-e">
            <h2>Contato</h2>
                <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
                Neque molestias eum dolor distinctio ea recusandae! Consequatur 
                sunt, dolore eos nemo minus, eveniet itaque in blanditiis iure 
                rerum, ipsum pariatur placeat!
                </p>
        </div>

    </div>

    </div>
  )
}
